runtime: python312 # または使用しているPythonのバージョン
entrypoint: gunicorn config.wsgi:application

env_variables:
  SECRET_KEY: your_secret_key_here # 本番環境では安全な値を設定
  DEBUG: "False"
  ALLOWED_HOSTS: ".appspot.com"
  # データベース接続情報 (Cloud SQLの場合)
  DB_NAME: your_db_name
  DB_USER: your_db_user
  DB_PASSWORD: your_db_password
  DB_HOST: /cloudsql/your-project-id:your-region:your-instance-name # Cloud SQL接続文字列
  DB_PORT: 5432

handlers:
# Vue.jsのビルド成果物 (index.html) をルートで提供
- url: /
  static_files: frontend/vue-project/dist/index.html
  upload: frontend/vue-project/dist/index.html
  secure: always
  redirect_http_response_code: 301

# Vue.jsの静的アセット (CSS, JSなど)
- url: /assets
  static_dir: frontend/vue-project/dist/assets
  secure: always
  redirect_http_response_code: 301

# Djangoの静的ファイル (collectstaticで集められたもの)
- url: /static
  static_dir: staticfiles
  secure: always
  redirect_http_response_code: 301

# Djangoアプリケーションへのルーティング
- url: /.*
  script: auto
  secure: always