# Generated by Django 5.2.5 on 2025-08-15 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DayGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100, unique=True, verbose_name='グループ名')),
                ('is_monday', models.BooleanField(default=False, verbose_name='月')),
                ('is_tuesday', models.BooleanField(default=False, verbose_name='火')),
                ('is_wednesday', models.BooleanField(default=False, verbose_name='水')),
                ('is_thursday', models.BooleanField(default=False, verbose_name='木')),
                ('is_friday', models.BooleanField(default=False, verbose_name='金')),
                ('is_saturday', models.BooleanField(default=False, verbose_name='土')),
                ('is_sunday', models.BooleanField(default=False, verbose_name='日')),
            ],
            options={
                'verbose_name': '曜日グループ',
                'verbose_name_plural': '曜日グループ',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='部門名')),
            ],
            options={
                'verbose_name': '部門',
                'verbose_name_plural': '部門',
            },
        ),
        migrations.CreateModel(
            name='RelationshipGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100, verbose_name='グループ名')),
                ('rule_type', models.CharField(choices=[('incompatible', '非互換'), ('pairing', 'ペアリング')], max_length=50, verbose_name='ルールの種類')),
            ],
            options={
                'verbose_name': '関係性グループ',
                'verbose_name_plural': '関係性グループ',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100, unique=True, verbose_name='スキル名')),
            ],
            options={
                'verbose_name': 'スキル',
                'verbose_name_plural': 'スキル',
            },
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='氏名')),
                ('employee_type', models.CharField(choices=[('hourly', '時給制'), ('salaried', '固定給')], default='hourly', max_length=10, verbose_name='雇用形態')),
                ('hourly_wage', models.IntegerField(blank=True, help_text='時給制の場合のみ入力', null=True, verbose_name='時給')),
                ('monthly_salary', models.IntegerField(blank=True, help_text='固定給の場合のみ入力', null=True, verbose_name='月給')),
                ('min_monthly_salary', models.IntegerField(blank=True, help_text='時給制メンバーの目標額', null=True, verbose_name='月の最低給与目標')),
                ('max_monthly_salary', models.IntegerField(blank=True, help_text='時給制メンバーの目標額', null=True, verbose_name='月の最高給与目標')),
                ('max_annual_salary', models.IntegerField(blank=True, help_text='例: 1030000', null=True, verbose_name='年間の最大給与額')),
                ('current_annual_salary', models.IntegerField(default=0, help_text='管理者が手動で更新します', verbose_name='現在の年間給与累計額')),
                ('salary_year_start_month', models.IntegerField(default=12, help_text='例: 12月始まりの場合「12」', verbose_name='給与年の開始月')),
                ('max_hours_per_day', models.IntegerField(default=8, verbose_name='1日の最大労働時間')),
                ('min_days_off_per_week', models.IntegerField(default=2, verbose_name='週の最低休日数')),
                ('min_monthly_days_off', models.IntegerField(default=8, verbose_name='月の最低公休日数')),
                ('enforce_exact_holidays', models.BooleanField(default=False, help_text='オンの場合、月の公休日数が設定通りに固定されます', verbose_name='休日数を固定する')),
                ('priority_score', models.IntegerField(default=10, verbose_name='割り当て優先度')),
                ('sort_order', models.IntegerField(default=99, help_text='数値が小さいほど上に表示されます', verbose_name='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('allowed_day_groups', models.ManyToManyField(blank=True, related_name='allowed_members', to='core.daygroup', verbose_name='勤務可能な曜日グループ')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.department', verbose_name='所属部門')),
            ],
            options={
                'verbose_name': '従業員',
                'verbose_name_plural': '従業員',
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_date', models.DateField(verbose_name='希望休の日付')),
                ('status', models.CharField(choices=[('approved', '承認'), ('pending', '申請中')], default='pending', max_length=50, verbose_name='状態')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.member', verbose_name='従業員')),
            ],
            options={
                'verbose_name': '希望休',
                'verbose_name_plural': '希望休登録',
            },
        ),
        migrations.CreateModel(
            name='MemberAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, '月曜日'), (1, '火曜日'), (2, '水曜日'), (3, '木曜日'), (4, '金曜日'), (5, '土曜日'), (6, '日曜日')], verbose_name='曜日')),
                ('start_time', models.TimeField(verbose_name='勤務可能開始時刻')),
                ('end_time', models.TimeField(verbose_name='勤務可能終了時刻')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.member', verbose_name='従業員')),
            ],
            options={
                'verbose_name': '勤務可能条件',
                'verbose_name_plural': '勤務可能条件',
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.member', verbose_name='従業員')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.relationshipgroup', verbose_name='グループ')),
            ],
            options={
                'verbose_name': 'グループ所属メンバー',
                'verbose_name_plural': 'グループ所属メンバー',
            },
        ),
        migrations.CreateModel(
            name='ShiftPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_name', models.CharField(max_length=100, verbose_name='パターン名')),
                ('start_time', models.TimeField(verbose_name='開始時刻')),
                ('end_time', models.TimeField(verbose_name='終了時刻')),
                ('break_minutes', models.IntegerField(default=60, verbose_name='休憩時間(分)')),
                ('is_night_shift', models.BooleanField(default=False, help_text='このシフトが夜勤の場合にチェック', verbose_name='夜勤シフト')),
                ('min_headcount', models.IntegerField(default=0, help_text='0の場合は無制限', verbose_name='このシフトの最低人数')),
                ('max_headcount', models.IntegerField(blank=True, help_text='空欄の場合は無制限', null=True, verbose_name='このシフトの最高人数')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department', verbose_name='部門')),
            ],
            options={
                'verbose_name': 'シフトパターン',
                'verbose_name_plural': 'シフトパターン',
            },
        ),
        migrations.CreateModel(
            name='MemberShiftPatternPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=10, help_text='数値が小さいほど優先されます', verbose_name='優先順位')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.member', verbose_name='従業員')),
                ('shift_pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shiftpattern', verbose_name='シフトパターン')),
            ],
            options={
                'verbose_name': 'シフトパターン優先度',
                'verbose_name_plural': 'シフトパターン優先度',
                'ordering': ['member', 'priority'],
                'unique_together': {('member', 'shift_pattern')},
            },
        ),
        migrations.AddField(
            model_name='member',
            name='shift_preferences',
            field=models.ManyToManyField(blank=True, help_text='ここで担当可能なシフトと、その優先順位を設定します', through='core.MemberShiftPatternPreference', to='core.shiftpattern', verbose_name='シフトパターンの優先度'),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateField(verbose_name='勤務日')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.member', verbose_name='従業員')),
                ('shift_pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shiftpattern', verbose_name='シフトパターン')),
            ],
            options={
                'verbose_name': '確定シフト',
                'verbose_name_plural': '確定シフト',
            },
        ),
        migrations.CreateModel(
            name='MemberSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.member', verbose_name='従業員')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.skill', verbose_name='スキル')),
            ],
            options={
                'verbose_name': '保有スキル',
                'verbose_name_plural': '保有スキル',
            },
        ),
        migrations.CreateModel(
            name='SpecificTimeSlotRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('start_time', models.TimeField(verbose_name='開始時刻')),
                ('end_time', models.TimeField(verbose_name='終了時刻')),
                ('min_headcount', models.IntegerField(verbose_name='最低必要人数')),
                ('max_headcount', models.IntegerField(blank=True, help_text='空欄の場合は上限なし', null=True, verbose_name='最大必要人数')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department', verbose_name='部門')),
            ],
            options={
                'verbose_name': '特定日別時間帯必要人数',
                'verbose_name_plural': '特定日別時間帯必要人数',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='TimeSlotRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='開始時刻')),
                ('end_time', models.TimeField(verbose_name='終了時刻')),
                ('min_headcount', models.IntegerField(verbose_name='最低必要人数')),
                ('max_headcount', models.IntegerField(blank=True, help_text='空欄の場合は上限なし', null=True, verbose_name='最大必要人数')),
                ('day_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.daygroup', verbose_name='曜日グループ')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department', verbose_name='部門')),
            ],
            options={
                'verbose_name': '時間帯別必要人数',
                'verbose_name_plural': '時間帯別必要人数',
            },
        ),
        migrations.CreateModel(
            name='OtherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateField(verbose_name='勤務日')),
                ('activity_name', models.CharField(max_length=100, verbose_name='業務内容')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.member', verbose_name='従業員')),
            ],
            options={
                'verbose_name': 'その他の割り当て',
                'verbose_name_plural': 'その他の割り当て',
                'unique_together': {('member', 'shift_date')},
            },
        ),
        migrations.CreateModel(
            name='FixedAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateField(verbose_name='勤務日')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.member', verbose_name='従業員')),
                ('shift_pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shiftpattern', verbose_name='シフトパターン')),
            ],
            options={
                'verbose_name': '固定シフト',
                'verbose_name_plural': '固定シフト',
                'unique_together': {('member', 'shift_date')},
            },
        ),
        migrations.CreateModel(
            name='SpecificDateRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('min_headcount', models.IntegerField(verbose_name='最低必要人数')),
                ('max_headcount', models.IntegerField(blank=True, help_text='空欄の場合は上限なし', null=True, verbose_name='最大必要人数')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department', verbose_name='部門')),
                ('shift_pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shiftpattern', verbose_name='シフトパターン')),
            ],
            options={
                'verbose_name': '特定日別シフト必要人数',
                'verbose_name_plural': '特定日別シフト必要人数',
                'unique_together': {('date', 'shift_pattern')},
            },
        ),
    ]
