# Generated by Django 5.2.5 on 2025-08-09 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='氏名')),
                ('hourly_wage', models.IntegerField(verbose_name='時給')),
                ('min_hours_per_week', models.IntegerField(default=0, verbose_name='週の最低労働時間')),
                ('max_hours_per_week', models.IntegerField(default=40, verbose_name='週の最大労働時間')),
                ('priority_score', models.IntegerField(default=10, verbose_name='割り当て優先度')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
        ),
        migrations.CreateModel(
            name='RelationshipGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100, verbose_name='グループ名')),
                ('rule_type', models.CharField(choices=[('incompatible', '非互換'), ('pairing', 'ペアリング')], max_length=50, verbose_name='ルールの種類')),
            ],
        ),
        migrations.CreateModel(
            name='ShiftPattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pattern_name', models.CharField(max_length=100, verbose_name='パターン名')),
                ('start_time', models.TimeField(verbose_name='開始時刻')),
                ('end_time', models.TimeField(verbose_name='終了時刻')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100, unique=True, verbose_name='スキル名')),
            ],
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_date', models.DateField(verbose_name='希望休の日付')),
                ('status', models.CharField(choices=[('approved', '承認'), ('pending', '申請中')], default='pending', max_length=50, verbose_name='状態')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.member', verbose_name='従業員')),
            ],
        ),
        migrations.CreateModel(
            name='MemberAvailability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, '日曜日'), (1, '月曜日'), (2, '火曜日'), (3, '水曜日'), (4, '木曜日'), (5, '金曜日'), (6, '土曜日')], verbose_name='曜日')),
                ('start_time', models.TimeField(verbose_name='勤務可能開始時刻')),
                ('end_time', models.TimeField(verbose_name='勤務可能終了時刻')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.member', verbose_name='従業員')),
            ],
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.member', verbose_name='従業員')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.relationshipgroup', verbose_name='グループ')),
            ],
        ),
        migrations.CreateModel(
            name='RequiredHeadcount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.IntegerField(choices=[(0, '日曜日'), (1, '月曜日'), (2, '火曜日'), (3, '水曜日'), (4, '木曜日'), (5, '金曜日'), (6, '土曜日')], verbose_name='曜日')),
                ('min_headcount', models.IntegerField(verbose_name='最低必要人数')),
                ('max_headcount', models.IntegerField(blank=True, null=True, verbose_name='推奨最大人数')),
                ('shift_pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shiftpattern', verbose_name='シフトパターン')),
            ],
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateField(verbose_name='勤務日')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.member', verbose_name='従業員')),
                ('shift_pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shiftpattern', verbose_name='シフトパターン')),
            ],
        ),
        migrations.CreateModel(
            name='MemberSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.member', verbose_name='従業員')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.skill', verbose_name='スキル')),
            ],
        ),
    ]
