# Generated by Django 5.2.5 on 2025-08-14 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100, unique=True, verbose_name='グループ名')),
                ('is_monday', models.BooleanField(default=False, verbose_name='月')),
                ('is_tuesday', models.BooleanField(default=False, verbose_name='火')),
                ('is_wednesday', models.BooleanField(default=False, verbose_name='水')),
                ('is_thursday', models.BooleanField(default=False, verbose_name='木')),
                ('is_friday', models.BooleanField(default=False, verbose_name='金')),
                ('is_saturday', models.BooleanField(default=False, verbose_name='土')),
                ('is_sunday', models.BooleanField(default=False, verbose_name='日')),
            ],
            options={
                'verbose_name': '曜日グループ',
                'verbose_name_plural': '曜日グループ',
            },
        ),
        migrations.CreateModel(
            name='SpecificTimeSlotRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('start_time', models.TimeField(verbose_name='開始時刻')),
                ('end_time', models.TimeField(verbose_name='終了時刻')),
                ('min_headcount', models.IntegerField(verbose_name='最低必要人数')),
                ('max_headcount', models.IntegerField(blank=True, help_text='空欄の場合は上限なし', null=True, verbose_name='最大必要人数')),
            ],
            options={
                'verbose_name': '特定日別時間帯必要人数',
                'verbose_name_plural': '特定日別時間帯必要人数',
                'ordering': ['date', 'start_time'],
            },
        ),
        migrations.AlterModelOptions(
            name='assignment',
            options={'verbose_name': '確定シフト', 'verbose_name_plural': '確定シフト'},
        ),
        migrations.AlterModelOptions(
            name='groupmember',
            options={'verbose_name': 'グループ所属メンバー', 'verbose_name_plural': 'グループ所属メンバー'},
        ),
        migrations.AlterModelOptions(
            name='leaverequest',
            options={'verbose_name': '希望休', 'verbose_name_plural': '希望休登録'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': '従業員', 'verbose_name_plural': '従業員'},
        ),
        migrations.AlterModelOptions(
            name='memberavailability',
            options={'verbose_name': '勤務可能条件', 'verbose_name_plural': '勤務可能条件'},
        ),
        migrations.AlterModelOptions(
            name='memberskill',
            options={'verbose_name': '保有スキル', 'verbose_name_plural': '保有スキル'},
        ),
        migrations.AlterModelOptions(
            name='relationshipgroup',
            options={'verbose_name': '関係性グループ', 'verbose_name_plural': '関係性グループ'},
        ),
        migrations.AlterModelOptions(
            name='shiftpattern',
            options={'verbose_name': 'シフトパターン', 'verbose_name_plural': 'シフトパターン'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'スキル', 'verbose_name_plural': 'スキル'},
        ),
        migrations.RemoveField(
            model_name='member',
            name='max_hours_per_week',
        ),
        migrations.RemoveField(
            model_name='member',
            name='min_hours_per_week',
        ),
        migrations.AddField(
            model_name='member',
            name='current_annual_salary',
            field=models.IntegerField(default=0, help_text='管理者が手動で更新します', verbose_name='現在の年間給与累計額'),
        ),
        migrations.AddField(
            model_name='member',
            name='employee_type',
            field=models.CharField(choices=[('hourly', '時給制'), ('salaried', '固定給')], default='hourly', max_length=10, verbose_name='雇用形態'),
        ),
        migrations.AddField(
            model_name='member',
            name='enforce_exact_holidays',
            field=models.BooleanField(default=False, help_text='オンの場合、月の公休日数が設定通りに固定されます', verbose_name='休日数を固定する'),
        ),
        migrations.AddField(
            model_name='member',
            name='max_annual_salary',
            field=models.IntegerField(blank=True, help_text='例: 1030000', null=True, verbose_name='年間の最大給与額'),
        ),
        migrations.AddField(
            model_name='member',
            name='max_hours_per_day',
            field=models.IntegerField(default=8, verbose_name='1日の最大労働時間'),
        ),
        migrations.AddField(
            model_name='member',
            name='max_monthly_salary',
            field=models.IntegerField(blank=True, help_text='時給制メンバーの目標額', null=True, verbose_name='月の最高給与目標'),
        ),
        migrations.AddField(
            model_name='member',
            name='min_days_off_per_week',
            field=models.IntegerField(default=2, verbose_name='週の最低休日数'),
        ),
        migrations.AddField(
            model_name='member',
            name='min_monthly_days_off',
            field=models.IntegerField(default=8, verbose_name='月の最低公休日数'),
        ),
        migrations.AddField(
            model_name='member',
            name='min_monthly_salary',
            field=models.IntegerField(blank=True, help_text='時給制メンバーの目標額', null=True, verbose_name='月の最低給与目標'),
        ),
        migrations.AddField(
            model_name='member',
            name='monthly_salary',
            field=models.IntegerField(blank=True, help_text='固定給の場合のみ入力', null=True, verbose_name='月給'),
        ),
        migrations.AddField(
            model_name='member',
            name='salary_year_start_month',
            field=models.IntegerField(default=12, help_text='例: 12月始まりの場合「12」', verbose_name='給与年の開始月'),
        ),
        migrations.AddField(
            model_name='member',
            name='sort_order',
            field=models.IntegerField(default=99, help_text='数値が小さいほど上に表示されます', verbose_name='表示順'),
        ),
        migrations.AddField(
            model_name='shiftpattern',
            name='break_minutes',
            field=models.IntegerField(default=60, verbose_name='休憩時間(分)'),
        ),
        migrations.AddField(
            model_name='shiftpattern',
            name='is_night_shift',
            field=models.BooleanField(default=False, help_text='このシフトが夜勤の場合にチェック', verbose_name='夜勤シフト'),
        ),
        migrations.AddField(
            model_name='shiftpattern',
            name='max_headcount',
            field=models.IntegerField(blank=True, help_text='空欄の場合は無制限', null=True, verbose_name='このシフトの最高人数'),
        ),
        migrations.AddField(
            model_name='shiftpattern',
            name='min_headcount',
            field=models.IntegerField(default=0, help_text='0の場合は無制限', verbose_name='このシフトの最低人数'),
        ),
        migrations.AlterField(
            model_name='member',
            name='hourly_wage',
            field=models.IntegerField(blank=True, help_text='時給制の場合のみ入力', null=True, verbose_name='時給'),
        ),
        migrations.AlterField(
            model_name='memberavailability',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, '月曜日'), (1, '火曜日'), (2, '水曜日'), (3, '木曜日'), (4, '金曜日'), (5, '土曜日'), (6, '日曜日')], verbose_name='曜日'),
        ),
        migrations.AddField(
            model_name='member',
            name='allowed_day_groups',
            field=models.ManyToManyField(blank=True, related_name='allowed_members', to='core.daygroup', verbose_name='勤務可能な曜日グループ'),
        ),
        migrations.CreateModel(
            name='FixedAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateField(verbose_name='勤務日')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.member', verbose_name='従業員')),
                ('shift_pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shiftpattern', verbose_name='シフトパターン')),
            ],
            options={
                'verbose_name': '固定シフト',
                'verbose_name_plural': '固定シフト',
                'unique_together': {('member', 'shift_date')},
            },
        ),
        migrations.CreateModel(
            name='MemberShiftPatternPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=10, help_text='数値が小さいほど優先されます', verbose_name='優先順位')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.member', verbose_name='従業員')),
                ('shift_pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shiftpattern', verbose_name='シフトパターン')),
            ],
            options={
                'verbose_name': 'シフトパターン優先度',
                'verbose_name_plural': 'シフトパターン優先度',
                'ordering': ['member', 'priority'],
                'unique_together': {('member', 'shift_pattern')},
            },
        ),
        migrations.AddField(
            model_name='member',
            name='shift_preferences',
            field=models.ManyToManyField(blank=True, help_text='ここで担当可能なシフトと、その優先順位を設定します', through='core.MemberShiftPatternPreference', to='core.shiftpattern', verbose_name='シフトパターンの優先度'),
        ),
        migrations.CreateModel(
            name='OtherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateField(verbose_name='勤務日')),
                ('activity_name', models.CharField(max_length=100, verbose_name='業務内容')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.member', verbose_name='従業員')),
            ],
            options={
                'verbose_name': 'その他の割り当て',
                'verbose_name_plural': 'その他の割り当て',
                'unique_together': {('member', 'shift_date')},
            },
        ),
        migrations.CreateModel(
            name='SpecificDateRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('min_headcount', models.IntegerField(verbose_name='最低必要人数')),
                ('max_headcount', models.IntegerField(blank=True, help_text='空欄の場合は上限なし', null=True, verbose_name='最大必要人数')),
                ('shift_pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shiftpattern', verbose_name='シフトパターン')),
            ],
            options={
                'verbose_name': '特定日別シフト必要人数',
                'verbose_name_plural': '特定日別シフト必要人数',
                'unique_together': {('date', 'shift_pattern')},
            },
        ),
        migrations.CreateModel(
            name='TimeSlotRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='開始時刻')),
                ('end_time', models.TimeField(verbose_name='終了時刻')),
                ('min_headcount', models.IntegerField(verbose_name='最低必要人数')),
                ('max_headcount', models.IntegerField(blank=True, help_text='空欄の場合は上限なし', null=True, verbose_name='最大必要人数')),
                ('day_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.daygroup', verbose_name='曜日グループ')),
            ],
            options={
                'verbose_name': '時間帯別必要人数',
                'verbose_name_plural': '時間帯別必要人数',
            },
        ),
        migrations.DeleteModel(
            name='RequiredHeadcount',
        ),
    ]
