# Generated by Django 5.2.5 on 2025-08-09 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DayGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100, unique=True, verbose_name='グループ名')),
                ('is_monday', models.BooleanField(default=False, verbose_name='月')),
                ('is_tuesday', models.BooleanField(default=False, verbose_name='火')),
                ('is_wednesday', models.BooleanField(default=False, verbose_name='水')),
                ('is_thursday', models.BooleanField(default=False, verbose_name='木')),
                ('is_friday', models.BooleanField(default=False, verbose_name='金')),
                ('is_saturday', models.BooleanField(default=False, verbose_name='土')),
                ('is_sunday', models.BooleanField(default=False, verbose_name='日')),
            ],
        ),
        migrations.RemoveField(
            model_name='requiredheadcount',
            name='day_of_week',
        ),
        migrations.AddField(
            model_name='requiredheadcount',
            name='day_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.daygroup', verbose_name='曜日グループ'),
        ),
    ]
