# Generated by Django 5.2.5 on 2025-08-15 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolverSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headcount_penalty_cost', models.IntegerField(default=1000000, verbose_name='必要人数不足ペナルティ')),
                ('headcount_surplus_penalty', models.IntegerField(default=800000, verbose_name='最高人数超過ペナルティ')),
                ('unavailable_day_penalty', models.IntegerField(default=70000, verbose_name='勤務不可曜日違反ペナルティ')),
                ('incompatible_penalty', models.IntegerField(default=60000, verbose_name='相性の悪いメンバー同時勤務ペナルティ')),
                ('holiday_violation_penalty', models.IntegerField(default=50000, verbose_name='月の最低公休日数違反ペナルティ')),
                ('salary_too_low_penalty', models.IntegerField(default=40000, verbose_name='給与目標最低額下回るペナルティ')),
                ('salary_too_high_penalty', models.IntegerField(default=30000, verbose_name='給与目標最高額上回るペナルティ')),
                ('difficulty_bonus_weight', models.IntegerField(default=10000, verbose_name='困難な日のシフトボーナス')),
                ('pairing_bonus', models.IntegerField(default=5000, verbose_name='ペアリングボーナス')),
                ('shift_preference_bonus', models.IntegerField(default=100, verbose_name='シフトパターン希望ボーナス')),
            ],
            options={
                'verbose_name': 'ソルバー設定',
                'verbose_name_plural': 'ソルバー設定',
            },
        ),
    ]
