# Generated by Django 5.2.5 on 2025-08-18 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaidLeave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('hours', models.IntegerField(default=8, help_text='有給としてカウントされる時間数', verbose_name='時間数')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.member', verbose_name='従業員')),
            ],
            options={
                'verbose_name': '有給',
                'verbose_name_plural': '有給',
                'unique_together': {('member', 'date')},
            },
        ),
    ]
