# Generated by Django 5.2.5 on 2025-08-09 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_daygroup_remove_requiredheadcount_day_of_week_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requiredheadcount',
            name='day_group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.daygroup', verbose_name='曜日グループ'),
            preserve_default=False,
        ),
    ]
