# Generated by Django 5.2.5 on 2025-08-15 19:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_solversettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SolverSettings',
        ),
    ]
