# Generated by Django 5.2.5 on 2025-08-18 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_paidleave'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'verbose_name': '確定シフト', 'verbose_name_plural': '4. シフト実績・申請 - 確定シフト'},
        ),
        migrations.AlterModelOptions(
            name='daygroup',
            options={'verbose_name': '曜日グループ', 'verbose_name_plural': '1. 基本設定 - 曜日グループ'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': '部門', 'verbose_name_plural': '1. 基本設定 - 部門'},
        ),
        migrations.AlterModelOptions(
            name='designatedholiday',
            options={'verbose_name': '指定休日', 'verbose_name_plural': '4. シフト実績・申請 - 指定休日'},
        ),
        migrations.AlterModelOptions(
            name='fixedassignment',
            options={'verbose_name': '固定シフト', 'verbose_name_plural': '4. シフト実績・申請 - 固定シフト'},
        ),
        migrations.AlterModelOptions(
            name='groupmember',
            options={'verbose_name': 'グループ所属メンバー', 'verbose_name_plural': '5. ソルバー・ルール設定 - グループ所属メンバー'},
        ),
        migrations.AlterModelOptions(
            name='leaverequest',
            options={'verbose_name': '希望休', 'verbose_name_plural': '4. シフト実績・申請 - 希望休'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': '従業員', 'verbose_name_plural': '2. 従業員管理 - 従業員'},
        ),
        migrations.AlterModelOptions(
            name='memberavailability',
            options={'verbose_name': '勤務可能条件', 'verbose_name_plural': '2. 従業員管理 - 勤務可能条件'},
        ),
        migrations.AlterModelOptions(
            name='membershiftpatternpreference',
            options={'ordering': ['member', 'priority'], 'verbose_name': 'シフトパターン優先度', 'verbose_name_plural': '2. 従業員管理 - シフトパターン優先度'},
        ),
        migrations.AlterModelOptions(
            name='memberskill',
            options={'verbose_name': '保有スキル', 'verbose_name_plural': '2. 従業員管理 - 保有スキル'},
        ),
        migrations.AlterModelOptions(
            name='otherassignment',
            options={'verbose_name': 'その他の割り当て', 'verbose_name_plural': '4. シフト実績・申請 - その他の割り当て'},
        ),
        migrations.AlterModelOptions(
            name='paidleave',
            options={'verbose_name': '有給', 'verbose_name_plural': '4. シフト実績・申請 - 有給'},
        ),
        migrations.AlterModelOptions(
            name='relationshipgroup',
            options={'verbose_name': '関係性グループ', 'verbose_name_plural': '5. ソルバー・ルール設定 - 関係性グループ'},
        ),
        migrations.AlterModelOptions(
            name='shiftpattern',
            options={'verbose_name': 'シフトパターン', 'verbose_name_plural': '3. シフトパターン・要件 - シフトパターン'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'スキル', 'verbose_name_plural': '1. 基本設定 - スキル'},
        ),
        migrations.AlterModelOptions(
            name='solversettings',
            options={'verbose_name': 'ソルバー設定', 'verbose_name_plural': '5. ソルバー・ルール設定 - ソルバー設定'},
        ),
        migrations.AlterModelOptions(
            name='specificdaterequirement',
            options={'verbose_name': '特定日別シフト必要人数', 'verbose_name_plural': '3. シフトパターン・要件 - 特定日別シフト必要人数'},
        ),
        migrations.AlterModelOptions(
            name='specifictimeslotrequirement',
            options={'ordering': ['date', 'start_time'], 'verbose_name': '特定日別時間帯必要人数', 'verbose_name_plural': '3. シフトパターン・要件 - 特定日別時間帯必要人数'},
        ),
        migrations.AlterModelOptions(
            name='timeslotrequirement',
            options={'verbose_name': '時間帯別必要人数', 'verbose_name_plural': '3. シフトパターン・要件 - 時間帯別必要人数'},
        ),
    ]
