# Generated by Django 5.2.5 on 2025-08-18 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_delete_solversettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='max_consecutive_work_days',
            field=models.PositiveIntegerField(blank=True, default=5, help_text='連続して勤務できる日数の上限', null=True, verbose_name='連続勤務数上限'),
        ),
    ]
