# Generated by Django 5.2.5 on 2025-08-11 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_requiredheadcount_day_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='max_hours_per_day',
            field=models.IntegerField(default=8, verbose_name='1日の最大労働時間'),
        ),
    ]
