# Generated by Django 5.0.14 on 2025-08-23 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_assignment_options_alter_daygroup_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MemberSkill',
        ),
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
