# Generated by Django 5.0.14 on 2025-08-28 12:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_memberskill_delete_skill'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'verbose_name': '確定シフト', 'verbose_name_plural': '16. 確定シフト'},
        ),
        migrations.AlterModelOptions(
            name='daygroup',
            options={'verbose_name': '曜日グループ', 'verbose_name_plural': '03. 曜日グループ'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'verbose_name': '部門', 'verbose_name_plural': '02. 部門'},
        ),
        migrations.AlterModelOptions(
            name='designatedholiday',
            options={'verbose_name': '指定休日', 'verbose_name_plural': '15. 指定休日'},
        ),
        migrations.AlterModelOptions(
            name='fixedassignment',
            options={'verbose_name': '固定シフト', 'verbose_name_plural': '13. 固定シフト'},
        ),
        migrations.AlterModelOptions(
            name='groupmember',
            options={'verbose_name': 'グループ所属メンバー', 'verbose_name_plural': '10. グループ所属メンバー'},
        ),
        migrations.AlterModelOptions(
            name='leaverequest',
            options={'verbose_name': '希望休', 'verbose_name_plural': '11. 希望休'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': '従業員', 'verbose_name_plural': '01. 従業員'},
        ),
        migrations.AlterModelOptions(
            name='memberavailability',
            options={'verbose_name': '勤務可能条件', 'verbose_name_plural': '04. 勤務可能条件'},
        ),
        migrations.AlterModelOptions(
            name='membershiftpatternpreference',
            options={'ordering': ['member', 'priority'], 'verbose_name': 'シフトパターン優先度', 'verbose_name_plural': '99. シフトパターン優先度'},
        ),
        migrations.AlterModelOptions(
            name='otherassignment',
            options={'verbose_name': 'その他の割り当て', 'verbose_name_plural': '14. その他の割り当て'},
        ),
        migrations.AlterModelOptions(
            name='paidleave',
            options={'verbose_name': '有給', 'verbose_name_plural': '12. 有給'},
        ),
        migrations.AlterModelOptions(
            name='relationshipgroup',
            options={'verbose_name': '関係性グループ', 'verbose_name_plural': '09. 関係性グループ'},
        ),
        migrations.AlterModelOptions(
            name='shiftpattern',
            options={'verbose_name': 'シフトパターン', 'verbose_name_plural': '05. シフトパターン'},
        ),
        migrations.AlterModelOptions(
            name='solversettings',
            options={'verbose_name': 'ソルバー設定', 'verbose_name_plural': '98. ソルバー設定'},
        ),
        migrations.AlterModelOptions(
            name='specificdaterequirement',
            options={'verbose_name': '特定日別シフト必要人数', 'verbose_name_plural': '07. 特定日別シフト必要人数'},
        ),
        migrations.AlterModelOptions(
            name='specifictimeslotrequirement',
            options={'ordering': ['date', 'start_time'], 'verbose_name': '特定日別時間帯必要人数', 'verbose_name_plural': '08. 特定日別時間帯必要人数'},
        ),
        migrations.AlterModelOptions(
            name='timeslotrequirement',
            options={'verbose_name': '時間帯別必要人数', 'verbose_name_plural': '06. 時間帯別必要人数'},
        ),
        migrations.AddField(
            model_name='department',
            name='managers',
            field=models.ManyToManyField(blank=True, related_name='managed_departments', to=settings.AUTH_USER_MODEL, verbose_name='管理者'),
        ),
    ]
