# Generated by Django 5.2.5 on 2025-08-18 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_member_max_consecutive_work_days'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignatedHoliday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='日付')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.member', verbose_name='従業員')),
            ],
            options={
                'verbose_name': '指定休日',
                'verbose_name_plural': '指定休日',
                'unique_together': {('member', 'date')},
            },
        ),
    ]
