# Generated by Django 5.2.5 on 2025-08-11 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_member_max_hours_per_day'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shiftpattern',
            options={'verbose_name': 'シフトパターン', 'verbose_name_plural': 'シフトパターン'},
        ),
        migrations.AddField(
            model_name='shiftpattern',
            name='break_minutes',
            field=models.IntegerField(default=60, verbose_name='休憩時間(分)'),
        ),
    ]
