# Generated by Django 5.2.5 on 2025-08-18 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_designatedholiday'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={},
        ),
        migrations.AlterModelOptions(
            name='shiftpattern',
            options={},
        ),
        migrations.RemoveField(
            model_name='member',
            name='allowed_day_groups',
        ),
        migrations.RemoveField(
            model_name='member',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='member',
            name='enforce_exact_holidays',
        ),
        migrations.RemoveField(
            model_name='member',
            name='priority_score',
        ),
        migrations.RemoveField(
            model_name='member',
            name='shift_preferences',
        ),
        migrations.RemoveField(
            model_name='member',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='shiftpattern',
            name='break_minutes',
        ),
        migrations.RemoveField(
            model_name='shiftpattern',
            name='is_night_shift',
        ),
        migrations.AddField(
            model_name='member',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=1),
        ),
        migrations.AddField(
            model_name='shiftpattern',
            name='min_female_headcount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shiftpattern',
            name='min_male_headcount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='member',
            name='max_consecutive_work_days',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='member',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='shiftpattern',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department'),
        ),
        migrations.AlterField(
            model_name='shiftpattern',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='shiftpattern',
            name='max_headcount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='shiftpattern',
            name='min_headcount',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='shiftpattern',
            name='pattern_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='shiftpattern',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
