# Generated by Django 5.2.5 on 2025-08-11 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_shiftpattern_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': '従業員', 'verbose_name_plural': '従業員'},
        ),
        migrations.AddField(
            model_name='member',
            name='employee_type',
            field=models.CharField(choices=[('hourly', '時給制'), ('salaried', '固定給')], default='hourly', max_length=10, verbose_name='雇用形態'),
        ),
        migrations.AddField(
            model_name='member',
            name='monthly_salary',
            field=models.IntegerField(blank=True, help_text='固定給の場合のみ入力', null=True, verbose_name='月給'),
        ),
        migrations.AlterField(
            model_name='member',
            name='hourly_wage',
            field=models.IntegerField(blank=True, help_text='時給制の場合のみ入力', null=True, verbose_name='時給'),
        ),
    ]
