# Generated by Django 5.2.5 on 2025-08-18 07:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_member_options_alter_shiftpattern_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='specifictimeslotrequirement',
            options={'verbose_name': '特定日タイムスロット要員数', 'verbose_name_plural': '特定日タイムスロット要員数'},
        ),
        migrations.AlterModelOptions(
            name='timeslotrequirement',
            options={},
        ),
        migrations.AddField(
            model_name='specifictimeslotrequirement',
            name='min_female_headcount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='specifictimeslotrequirement',
            name='min_male_headcount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timeslotrequirement',
            name='min_female_headcount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='timeslotrequirement',
            name='min_male_headcount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='specifictimeslotrequirement',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='specifictimeslotrequirement',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department'),
        ),
        migrations.AlterField(
            model_name='specifictimeslotrequirement',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='specifictimeslotrequirement',
            name='max_headcount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='specifictimeslotrequirement',
            name='min_headcount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='specifictimeslotrequirement',
            name='start_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='timeslotrequirement',
            name='day_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.daygroup'),
        ),
        migrations.AlterField(
            model_name='timeslotrequirement',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.department'),
        ),
        migrations.AlterField(
            model_name='timeslotrequirement',
            name='end_time',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='timeslotrequirement',
            name='max_headcount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='timeslotrequirement',
            name='min_headcount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='timeslotrequirement',
            name='start_time',
            field=models.TimeField(),
        ),
    ]
