# Generated by Django 5.2.5 on 2025-08-11 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_member_options_member_employee_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='max_monthly_salary',
            field=models.IntegerField(blank=True, help_text='時給制メンバーの目標額', null=True, verbose_name='月の最高給与目標'),
        ),
        migrations.AddField(
            model_name='member',
            name='min_monthly_salary',
            field=models.IntegerField(blank=True, help_text='時給制メンバーの目標額', null=True, verbose_name='月の最低給与目標'),
        ),
    ]
