# Generated by Django 5.0.6 on 2024-08-29 08:30

from django.db import migrations

def create_default_staff_group(apps, schema_editor):
    """
    Creates the "Default Staff" group and assigns all permissions for the "core" app.
    """
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    GROUP_NAME = "Default Staff"

    # Get or create the group
    group, created = Group.objects.get_or_create(name=GROUP_NAME)

    # Get all content types for the 'core' app
    core_content_types = ContentType.objects.filter(app_label='core')

    # Get all permissions for those content types
    core_permissions = Permission.objects.filter(content_type__in=core_content_types)

    # Assign all core permissions to the group
    group.permissions.set(core_permissions)

    if created:
        print(f'Group "{GROUP_NAME}" created and all core permissions assigned.')
    else:
        print(f'Group "{GROUP_NAME}" already existed. All core permissions have been reassigned.')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_populate_created_by'),
    ]

    operations = [
        migrations.RunPython(create_default_staff_group),
    ]