# Generated by Django 5.2.5 on 2025-08-11 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_member_max_monthly_salary_member_min_monthly_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='current_annual_salary',
            field=models.IntegerField(default=0, help_text='管理者が手動で更新します', verbose_name='現在の年間給与累計額'),
        ),
        migrations.AddField(
            model_name='member',
            name='max_annual_salary',
            field=models.IntegerField(blank=True, help_text='例: 1030000', null=True, verbose_name='年間の最大給与額'),
        ),
        migrations.AddField(
            model_name='member',
            name='salary_year_start_month',
            field=models.IntegerField(default=12, help_text='例: 12月始まりの場合「12」', verbose_name='給与年の開始月'),
        ),
    ]
