# Generated by Django 5.0.14 on 2025-08-29 18:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_create_default_staff_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='daygroup',
            name='group_name',
            field=models.CharField(max_length=100, verbose_name='グループ名'),
        ),
        migrations.AlterUniqueTogether(
            name='daygroup',
            unique_together={('group_name', 'created_by')},
        ),
    ]
