# Generated by Django 5.2.5 on 2025-08-11 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_member_current_annual_salary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='assignable_patterns',
            field=models.ManyToManyField(blank=True, help_text='空の場合、全てのシフトパターンが担当可能と見なされます', to='core.shiftpattern', verbose_name='担当可能なシフト'),
        ),
    ]
