# Generated by Django 5.0.14 on 2025-08-30 06:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_daygroup_group_name_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memberavailability',
            name='day_of_week',
        ),
        migrations.AddField(
            model_name='memberavailability',
            name='is_friday',
            field=models.BooleanField(default=False, verbose_name='金'),
        ),
        migrations.AddField(
            model_name='memberavailability',
            name='is_monday',
            field=models.BooleanField(default=False, verbose_name='月'),
        ),
        migrations.AddField(
            model_name='memberavailability',
            name='is_saturday',
            field=models.BooleanField(default=False, verbose_name='土'),
        ),
        migrations.AddField(
            model_name='memberavailability',
            name='is_sunday',
            field=models.BooleanField(default=False, verbose_name='日'),
        ),
        migrations.AddField(
            model_name='memberavailability',
            name='is_thursday',
            field=models.BooleanField(default=False, verbose_name='木'),
        ),
        migrations.AddField(
            model_name='memberavailability',
            name='is_tuesday',
            field=models.BooleanField(default=False, verbose_name='火'),
        ),
        migrations.AddField(
            model_name='memberavailability',
            name='is_wednesday',
            field=models.BooleanField(default=False, verbose_name='水'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, verbose_name='部門名'),
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('name', 'created_by')},
        ),
    ]
