# Generated by Django 5.2.5 on 2025-08-11 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_member_assignable_patterns'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='allowed_day_groups',
            field=models.ManyToManyField(blank=True, related_name='allowed_members', to='core.daygroup', verbose_name='勤務可能な曜日グループ'),
        ),
        migrations.AddField(
            model_name='shiftpattern',
            name='is_night_shift',
            field=models.BooleanField(default=False, help_text='このシフトが夜勤の場合にチェック', verbose_name='夜勤シフト'),
        ),
    ]
