# Generated by Django 5.2.5 on 2025-08-11 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_member_allowed_day_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='min_days_off_per_week',
            field=models.IntegerField(default=2, verbose_name='週の最低休日数'),
        ),
    ]
