# Generated by Django 5.2.5 on 2025-08-12 02:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_member_min_days_off_per_week'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlotRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(verbose_name='開始時刻')),
                ('end_time', models.TimeField(verbose_name='終了時刻')),
                ('min_headcount', models.IntegerField(verbose_name='最低必要人数')),
                ('day_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.daygroup', verbose_name='曜日グループ')),
            ],
            options={
                'verbose_name': '時間帯別必要人数',
                'verbose_name_plural': '時間帯別必要人数',
            },
        ),
        migrations.DeleteModel(
            name='RequiredHeadcount',
        ),
    ]
