# Generated by Django 5.2.5 on 2025-08-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_timeslotrequirement_delete_requiredheadcount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='max_hours_per_week',
        ),
        migrations.RemoveField(
            model_name='member',
            name='min_hours_per_week',
        ),
        migrations.AddField(
            model_name='member',
            name='min_monthly_days_off',
            field=models.IntegerField(default=8, verbose_name='月の最低公休日数'),
        ),
    ]
