# Generated by Django 5.2.5 on 2025-08-12 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_member_max_hours_per_week_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslotrequirement',
            name='max_headcount',
            field=models.IntegerField(blank=True, help_text='空欄の場合は上限なし', null=True, verbose_name='最大必要人数'),
        ),
    ]
