# Generated by Django 5.2.5 on 2025-08-12 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_timeslotrequirement_max_headcount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='min_monthly_days_off',
        ),
    ]
