# Generated by Django 5.2.5 on 2025-08-13 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_member_min_monthly_days_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='min_monthly_days_off',
            field=models.IntegerField(default=8, verbose_name='月の最低公休日数'),
        ),
    ]
