# Generated by Django 5.2.5 on 2025-08-13 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_member_min_monthly_days_off'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='sort_order',
            field=models.IntegerField(default=99, help_text='数値が小さいほど上に表示されます', verbose_name='表示順'),
        ),
    ]
