# Generated by Django 5.2.5 on 2025-08-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_member_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='shiftpattern',
            name='max_headcount',
            field=models.IntegerField(blank=True, help_text='空欄の場合は無制限', null=True, verbose_name='このシフトの最高人数'),
        ),
        migrations.AddField(
            model_name='shiftpattern',
            name='min_headcount',
            field=models.IntegerField(default=0, help_text='0の場合は無制限', verbose_name='このシフトの最低人数'),
        ),
    ]
