# Generated by Django 5.2.5 on 2025-08-13 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_shiftpattern_max_headcount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='enforce_exact_holidays',
            field=models.BooleanField(default=False, help_text='オンの場合、月の公休日数が設定通りに固定されます', verbose_name='休日数を固定する'),
        ),
    ]
