# Generated by Django 5.2.5 on 2025-08-13 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_member_enforce_exact_holidays'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateField(verbose_name='勤務日')),
                ('activity_name', models.CharField(max_length=100, verbose_name='業務内容')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.member', verbose_name='従業員')),
            ],
            options={
                'verbose_name': 'その他の割り当て',
                'verbose_name_plural': 'その他の割り当て',
                'unique_together': {('member', 'shift_date')},
            },
        ),
    ]
