# Generated by Django 5.2.5 on 2025-08-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_otherassignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'verbose_name': '確定シフト', 'verbose_name_plural': '確定シフト'},
        ),
        migrations.AlterModelOptions(
            name='daygroup',
            options={'verbose_name': '曜日グループ', 'verbose_name_plural': '曜日グループ'},
        ),
        migrations.AlterModelOptions(
            name='groupmember',
            options={'verbose_name': 'グループ所属メンバー', 'verbose_name_plural': 'グループ所属メンバー'},
        ),
        migrations.AlterModelOptions(
            name='leaverequest',
            options={'verbose_name': '希望休', 'verbose_name_plural': '希望休登録'},
        ),
        migrations.AlterModelOptions(
            name='memberavailability',
            options={'verbose_name': '勤務可能条件', 'verbose_name_plural': '勤務可能条件'},
        ),
        migrations.AlterModelOptions(
            name='memberskill',
            options={'verbose_name': '保有スキル', 'verbose_name_plural': '保有スキル'},
        ),
        migrations.AlterModelOptions(
            name='otherassignment',
            options={'verbose_name': '固定業務', 'verbose_name_plural': '固定業務'},
        ),
        migrations.AlterModelOptions(
            name='relationshipgroup',
            options={'verbose_name': '関係性グループ', 'verbose_name_plural': '関係性グループ'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'verbose_name': 'スキル', 'verbose_name_plural': 'スキル'},
        ),
        migrations.AlterField(
            model_name='memberavailability',
            name='day_of_week',
            field=models.IntegerField(choices=[(0, '月曜日'), (1, '火曜日'), (2, '水曜日'), (3, '木曜日'), (4, '金曜日'), (5, '土曜日'), (6, '日曜日')], verbose_name='曜日'),
        ),
    ]
