# Generated by Django 5.2.5 on 2025-08-14 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_assignment_options_alter_daygroup_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_date', models.DateField(verbose_name='勤務日')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.member', verbose_name='従業員')),
                ('shift_pattern', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shiftpattern', verbose_name='シフトパターン')),
            ],
            options={
                'verbose_name': '固定シフト',
                'verbose_name_plural': '固定シフト',
                'unique_together': {('member', 'shift_date')},
            },
        ),
    ]
