# Generated by Django 5.2.5 on 2025-08-14 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_fixedassignment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'verbose_name': 'シフト割り当て', 'verbose_name_plural': 'シフト割り当て'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ['sort_order', 'id'], 'verbose_name': '従業員', 'verbose_name_plural': '従業員'},
        ),
        migrations.AlterModelOptions(
            name='otherassignment',
            options={'verbose_name': 'その他業務', 'verbose_name_plural': 'その他業務'},
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('member', 'shift_date')},
        ),
        migrations.AlterUniqueTogether(
            name='groupmember',
            unique_together={('group', 'member')},
        ),
        migrations.AlterUniqueTogether(
            name='leaverequest',
            unique_together={('member', 'leave_date')},
        ),
        migrations.AlterUniqueTogether(
            name='memberavailability',
            unique_together={('member', 'day_of_week')},
        ),
        migrations.AlterUniqueTogether(
            name='memberskill',
            unique_together={('member', 'skill')},
        ),
    ]
