# Generated by Django 5.2.5 on 2025-08-14 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_alter_assignment_options_alter_member_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'verbose_name': '確定シフト', 'verbose_name_plural': '確定シフト'},
        ),
        migrations.AlterModelOptions(
            name='member',
            options={'verbose_name': '従業員', 'verbose_name_plural': '従業員'},
        ),
        migrations.AlterModelOptions(
            name='otherassignment',
            options={'verbose_name': 'その他の割り当て', 'verbose_name_plural': 'その他の割り当て'},
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='groupmember',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='leaverequest',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='memberavailability',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='memberskill',
            unique_together=set(),
        ),
    ]
